version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 52729bbe50d1d3f27774761a3ae11ce34b3a14fbbdfdce903f8736eac52f30c5

    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/louy/terraform-provider-uptimerobot

    steps:
      - checkout

      - restore_cache:
          keys:
            - vendor-dep-{{ checksum "Gopkg.lock" }}

      - run: dep ensure -vendor-only -v

      - save_cache:
          key: vendor-dep-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Build
          command: |
            go build -v
      - run:
          name: Run acceptance tests
          command: |
            ./cc-test-reporter before-build
            TF_ACC=1 go test -coverprofile c.out -v ./...
            ./cc-test-reporter after-build --exit-code $?

      - store_artifacts:
          path: "/go/bin/terraform-provider-uptimerobot"
          destination: terraform-provider-uptimerobot

      - deploy:
          name: goreleaser
          command: |
            if [[ -n ${CIRCLE_TAG} ]]; then
              curl -sL https://git.io/goreleaser | bash
            fi

      - store_artifacts:
          path: "/go/src/terraform-provider-uptimerobot/dist"
          destination: dist

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
