version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/louy/terraform-provider-uptimerobot

    steps:
      - checkout

      - restore_cache:
          keys:
            - vendor-dep-{{ checksum "Gopkg.lock" }}

      - run: dep ensure -vendor-only -v

      - save_cache:
          key: vendor-dep-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor

      - run:
          name: Build
          command: |
            go build -v
      - run:
          name: Run acceptance tests
          command: |
            TF_ACC=1 go test -v ./...

      - store_artifacts:
          path: "/go/bin/terraform-provider-uptimerobot"
          destination: terraform-provider-uptimerobot

      - deploy:
          name: goreleaser
          command: |
            if [[ -n ${CIRCLE_TAG} ]]; then
              curl -sL https://git.io/goreleaser | bash
            fi

      - store_artifacts:
          path: "/go/src/terraform-provider-uptimerobot/dist"
          destination: dist

workflows:
  version: 2

  build:
    jobs:
      - build
    filters:
      branches:
        only: /.*/
      tags:
        only: /.*/
