name: test
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths:
      - uptimerobot/*
      - go.sum
      - go.mod
      - main.go
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12
      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('go.sum') }}
      - name: Setup Code Climate test-reporter
        run: |
          # download test reporter as a static binary
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      - name: Build
        run: |
          go build -v
      - name: Run acceptance tests
        run: |
          ./cc-test-reporter before-build
          TF_ACC=1 go test -coverprofile c.out -v ./...
          ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: 52729bbe50d1d3f27774761a3ae11ce34b3a14fbbdfdce903f8736eac52f30c5
